spring:
  datasource:
    username: root
    password: chenzy88
    url: jdbc:mysql://47.99.57.25:3306/chenzy?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 47.99.57.25
    port: 6379
    timeout: 20000
    password: chenzy88
    pool:
      max-active: 8
      min-idle: 0
      max-idle: 8
      max-wait: -1
    application:
      name: spring-boot-redis
  rabbitmq:
    host: 47.99.57.25
    port: 5672 #不是15672。客户端就是5672
    username: chenzy88
    password: chenzy88
    virtual-host: chenzydev
    listener:
      simple:
        #acknowledge-mode: manual #设置确认模式手工确认
        concurrency: 3 #消费者最小数量
        max-concurrency: 10 # 消费者最大数量